### PR TITLE
Add Windows support

### PR DESCRIPTION
**Pull request by ChristianMurphy**
See https://github.com/nodejs/node-v0.x-archive/issues/2318 for context

### CODE REVIEW

**Comment by danmactough** [comment]
wow that thread...

the [docs](https://nodejs.org/dist/latest-v6.x/docs/api/child_process.html#child_process_child_process_spawn_command_args_options) are actually pretty good though

**Comment by danmactough** [comment]
published as v2.0.0

**Comment by ChristianMurphy** [comment]
Thanks @danmactough!

**Comment by danmactough** [comment]
Thank YOU!!

**Pull request merged**
